[[constraint]]
  branch = "master"
  name = "github.com/getlantern/systray"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-github"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
